apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quinoa-wind-turbine-iw7o
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quinoa-wind-turbine-iw7o
    app.kubernetes.io/part-of: imported-turbine
  name: quinoa-wind-turbine-iw7o
  namespace: user1-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: quinoa-wind-turbine-iw7o
status:
  loadBalancer: {}
